### ISSUE TITLE
No commands in sail-ssl namespace

### ISSUE THREAD

**Issue by stephenr85** [ryoluo/sail-ssl#15]
In Laravel 10.10, when I try to run the package commands, I get 

```
ERROR  There are no commands defined in the "sail-ssl" namespace.  
```

At a glance, it looks like you're registering them correctly with the commands() method of your service provider, so I'm not sure what the issue is. I can confirm the service provider is loading and the registerCommands method is being called.

If I add this to my console kernel, they work.
```php
   protected $commands = [
       \Ryoluo\SailSsl\Console\InstallCommand::class,
        \Ryoluo\SailSsl\Console\PublishCommand::class
    ];
```

**Comment by ryoluo** [comment]
Could you check this issue?
https://github.com/ryoluo/sail-ssl/issues/14
