### ISSUE TITLE
Issue with certificate loading

### ISSUE THREAD

**Issue by zekson266** [ryoluo/sail-ssl#16]
I got certificates by certbot certonly (fullchaine.pem & privkey.pem), indicate path in yml 'sail-nginx:/etc/letsencrypt/live/site.domain/' but still failure: (I even copied fullchaine.pem as server.pem to mentioned path without result, also I updated rights by sudo chmod -R 775 , but without result)

mfa-nginx-1         | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
mfa-nginx-1         | /docker-entrypoint.sh: Launching /docker-entrypoint.d/99-generate-ssl-cert.sh
mfa-nginx-1         | 99-generate-ssl-cert.sh: Server certificate already exists, do nothing.
mfa-nginx-1         | /docker-entrypoint.sh: Configuration complete; ready for start up
mfa-nginx-1         | 2023/09/11 19:26:26 [emerg] 1#1: cannot load certificate "/etc/nginx/certs/server.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/certs/server.pem, r) error:10000080:BIO routines::no such file)
mfa-nginx-1         | nginx: [emerg] cannot load certificate "/etc/nginx/certs/server.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/certs/server.pem, r) error:10000080:BIO routines::no such file)

**Comment by ryoluo** [comment]
Your issue may not be caused by library, but by environment settings.
Please note that Laravel Sail and this plugin is NOT for production.

**Comment by zekson266** [comment]
Thanks for reply, is this means that Sail projects not for production at all due to absence of SSL feature?

**Comment by ryoluo** [comment]
Laravel Sail has lack of security features because it is only for development.
Although this plugin support HTTPS connection, Laravel Sail is still for development  purpose, not for production deployment.

**Comment by zekson266** [comment]
Thanks for feedback, got you. Now I'm starting to learn how to create Laravel app without Sail, just with Docker.

**Comment by tobz-nz** [comment]
Another reason for this or similar issue is not having the new ENV variables: `SSL_DOMAIN` & `SSL_ALT_NAME`.
Adding those to `docker-compose.yml` fixed it for me.
