### ISSUE TITLE
Your connection is not private

### ISSUE THREAD

**Issue by abr4xas** [ryoluo/sail-ssl#2]
Any advice on how to make it work ?

![image](https://user-images.githubusercontent.com/405484/180614324-5ec0b50f-7376-4d88-8df3-1cd4cc08f955.png)

**Comment by ryoluo** [comment]
You just need to click "Advanced" then "Continue to localhost (unsafe)" to access your application.
*The warning from the browser is normal behavior because the server uses a self-signed certificate.

**Comment by ryoluo** [comment]
@aguvillalba 
I got it. Actually this is not a library's issue, but you can ignore the caution by typing "thisisunsafe" on the page.
Ref: https://snippets.khromov.se/bypass-chrome-self-signed-certificate-not-working-error-page/

**Comment by maurocasas** [comment]
When you get to this screen, you may type `thisisunsafe` in the "air", and it'll overpass this.

Meaning, on this page, you don't click anything, just type that and it'll continue.

**Comment by mreduar** [comment]
Isn't the purpose of having SSL is that the local certificate is valid? For example, in Laragon the certificate .crt is added to TrustStore.

**Comment by ryoluo** [comment]
Validation of self-signed certificate is out of  scope because it is the issue of the SSL client, not the server.

**Comment by GingerN** [comment]
Very convenient plugin. Thank you.

For this question I want to advice this answer by kellen for google chrome
https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate
