### ISSUE TITLE
Missing custom http(s) port

### ISSUE THREAD

**Issue by Cyrille37** [ryoluo/sail-ssl#21]
Hi,
Thanks for your great package and to share it :-)

To make it compatible with custom port and host we have to provide headers used by laravel/symfony `X_FORWARDED_HOST`, `X_FORWARDED_PROTO` and `X_FORWARDED_PORT` in the nginx configuration.

```
map $http_host $port {
    default 80;
    "~^[^\:]+:(?<p>\d+)$" $p;
}

server {
    ...
    location / {
        ...
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $port;
        ...
```

**Comment by ryoluo** [comment]
Hi @Cyrille37 !
Thank you very much for your proposal.
`X-Forwarded-Host` and `X-Forwarded-Port` headers are supported on [v1.3.1](https://github.com/ryoluo/sail-ssl/releases/tag/v1.3.1).
