### ISSUE TITLE
Reissue the certificate

### ISSUE THREAD

**Issue by dosinabox** [ryoluo/sail-ssl#25]
I accidentally installed this with the incorrect options in my `.env` file (for `localhost`). Is it possible to regenerate the certificate again for my actual domain?

**Comment by dosinabox** [comment]
Got it: just repeat the `generate-ssl-cert.sh` command inside nginx container.

**Comment by ryoluo** [comment]
FYI: you can re-issue certs by remove certs from Docker volume: sail-nginx.
