### ISSUE TITLE
Navigator shows 'Not secure'

### ISSUE THREAD

**Issue by XanXus96** [ryoluo/sail-ssl#4]
the navigator shows 'not secure' on the certificate with barred red https
![image](https://user-images.githubusercontent.com/39890594/205542081-776229c9-fd2c-4a13-bc79-414c776b41cb.png)

**Comment by ryoluo** [comment]
It is normal behaviour because server uses self-signed certificate. Laravel Sail and this plugin is not for use in production.

**Comment by ErichKramer** [comment]
Can you elaborate, or provide the relevant discourse on why laravel sail is not intended for production use?

E.G., what is to stop me from getting a legitimate certificate and throwing it into the correct location, and why should I not do this?
